import socket
import pathlib
from PyQt6 import uic
from PyQt6.QtWidgets import QWidget, QApplication, QMessageBox, QLabel, QMainWindow
from PyQt6.QtGui import QImage, QPixmap, QColor, QPainter
import zipfile
import os
import sys


# Form implementation generated from reading ui file 'installer.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(314, 435)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 301, 421))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(parent=self.page)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.page)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 161, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.page)
        self.label_3.setGeometry(QtCore.QRect(170, 30, 111, 121))
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.page)
        self.pushButton.setGeometry(QtCore.QRect(164, 350, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(110, 90, 181, 20))
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(50)
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(parent=self.page_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.page_2)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.page_2)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 91, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.page_2)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 151, 16))
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 130, 75, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(parent=self.page_2)
        self.label_8.setEnabled(True)
        self.label_8.setGeometry(QtCore.QRect(40, 150, 241, 231))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.label_8.setFont(font)
        self.label_8.setLineWidth(1)
        self.label_8.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_8.setIndent(-1)
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_3.setGeometry(QtCore.QRect(164, 390, 131, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 390, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_12 = QtWidgets.QLabel(parent=self.page_2)
        self.label_12.setEnabled(True)
        self.label_12.setGeometry(QtCore.QRect(20, 110, 151, 16))
        self.label_12.setObjectName("label_12")
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_13 = QtWidgets.QLabel(parent=self.page_4)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.page_4)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 281, 91))
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.page_4)
        self.label_15.setGeometry(QtCore.QRect(20, 100, 71, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.page_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(82, 100, 191, 20))
        self.lineEdit_2.setMaxLength(200)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.page_4)
        self.pushButton_6.setGeometry(QtCore.QRect(144, 382, 151, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.page_4)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 380, 81, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_9 = QtWidgets.QLabel(parent=self.page_3)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.page_3)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.page_3)
        self.label_11.setGeometry(QtCore.QRect(150, 20, 131, 121))
        self.label_11.setText("")
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton_5.setGeometry(QtCore.QRect(184, 362, 91, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.page_3)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "UTI"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p>Добро пожаловать в</p><p>установщик современного</p><p>расширения для</p><p>изображений UTI!</p></body></html>"))
        self.pushButton.setText(_translate("Form", "Далее"))
        self.label_4.setText(_translate("Form", "Ключ активации"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p>Введите ключ активации и выполните все пункты из</p><p>руководства по установке.</p></body></html>"))
        self.label_6.setText(_translate("Form", "Ключ активации:"))
        self.label_7.setText(_translate("Form", "Руководство по установке"))
        self.pushButton_2.setText(_translate("Form", "Показать"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p>1. Установите программу Radmin Vpn.</p><p>2. Подключитесь к частной сети &quot;UTI Images&quot;</p><p>с паролем &quot;uti_images&quot; в установленной</p><p>программе.</p><p>3. Введите ключ активации, полученный из</p><p>телеграм бота @uti_images_bot.</p><p>4. <span style=\" font-weight:600;\">Убедитесь в стабильности интернет</span></p><p><span style=\" font-weight:600;\">соединения.</span></p><p>5. Нажмите &quot;Далее&quot;.</p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "Далее"))
        self.pushButton_4.setText(_translate("Form", "Назад"))
        self.label_12.setText(_translate("Form", "Осталось попыток: 3"))
        self.label_13.setText(_translate("Form", "Обновления"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p>Для получения обновлений введите ваш username в</p><p>Telegram. Этот шаг можно будет выполнить позже.</p></body></html>"))
        self.label_15.setText(_translate("Form", "Username:"))
        self.pushButton_6.setText(_translate("Form", "Далее"))
        self.pushButton_7.setText(_translate("Form", "Пропустить"))
        self.label_9.setText(_translate("Form", "Поздравляем!"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p>Вы успешно установили UTI</p><p>и можете им пользоваться.</p></body></html>"))
        self.pushButton_5.setText(_translate("Form", "Закрыть"))


HOST = '26.201.31.50'
PORT = 65432
TEMP = pathlib.Path.home() / 'AppData' / 'Local' / 'Temp' / 'UTI' / 'First'
FILES_TEMP = pathlib.Path.home() / 'AppData' / 'Local' / 'Temp' / 'UTI' / 'files.zip'
UPD_DATA = pathlib.Path.home() / 'AppData' / 'Local' / 'MaksMesh' / 'UTI' / 'Updater' / 'data.txt'


class LoadingWindow(QMainWindow):
    def __init__(self, parent):
        super().__init__(parent)
        self.initUI()

    def initUI(self):
        self.setWindowTitle('Загрузка')
        self.setFixedSize(200, 100)

        self.label = QLabel(self)
        self.label.setFixedSize(200, 30)
        self.label.move(10, 30)

    def change_status(self, text):
        self.label.setText(text)


class Installer(QWidget, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.current_page = 0
        self.instr_showed = False 
        self.loading = None
        self.attempts = 5
        self.initUI()

    def initUI(self):
        self.setWindowTitle('Установщик')
        self.setFixedSize(314, 435)

        self.pushButton.clicked.connect(self.next_page)
        self.pushButton_4.clicked.connect(self.prev_page)
        self.pushButton_2.clicked.connect(self.show_information)
        self.pushButton_3.clicked.connect(self.activate_key)
        self.pushButton_7.clicked.connect(self.skip)
        self.pushButton_6.clicked.connect(self.next_upd)
        self.pushButton_5.clicked.connect(self.close)

        self.label_12.hide()
        self.label_8.hide()

        self.draw_icons()

    def next_page(self):
        self.current_page += 1
        self.stackedWidget.setCurrentIndex(self.current_page)

    def prev_page(self):
        self.current_page -= 1
        self.stackedWidget.setCurrentIndex(self.current_page)

    def show_information(self):
        if not self.instr_showed:
            self.label_8.show()
            self.pushButton_2.setText('Спрятать')
            self.instr_showed = True
        else:
            self.label_8.hide()
            self.pushButton_2.setText('Показать')
            self.instr_showed = False

    def activate_key(self):
        if self.loading is None:
            key = self.lineEdit.text()
            if key:
                self.loading = LoadingWindow(self)
                self.loading.change_status('Обращение к серверу...')
                self.loading.show()

                try:
                    if self.check_key(key):
                        self.key = key
                        self.loading.change_status('Распаковка файлов...')
                        file = zipfile.ZipFile(FILES_TEMP)
                        file.extractall(TEMP)
                        file.close()
                        self.loading.change_status('Установка...')
                        os.system('Powershell -Command "& { Start-Process \"' + str(TEMP / 'execute.exe') + '\" -Verb RunAs }')
                        self.loading.close()
                        self.loading = None
                        self.attempts = 5
                        self.next_page()
                    else:
                        self.attempts -= 1
                        self.loading.close()
                        self.loading = None

                        if self.attempts == 3:
                            self.label_12.show()
                        elif self.attempts == 2:
                            self.label_12.setText('Осталось попыток: 2')
                        elif self.attempts == 1:
                            self.label_12.setText('Осталось попыток: 1')
                        elif self.attempts == 0:
                            self.close()

                        QMessageBox.critical(self, 'Ошибка', 'Неверный ключ!')
                except ConnectionRefusedError:
                    self.loading.close()
                    self.loading = None
                    QMessageBox.critical(self, 'Ошибка', 'Нет подключения к серверу.')
            else:
                QMessageBox.critical(self, 'Ошибка', 'Введите ключ!')

    def check_key(self, key):
        p = pathlib.Path.home() / 'AppData' / 'Local' / 'Temp' / 'UTI'
        p.mkdir(exist_ok=True)

        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.connect((HOST, PORT))
            s.sendall(b'id ' + bytes(key, 'UTF-8'))
            data = s.recv(4)
            
            if data == b'FILE':
                data = s.recv(1024)

                with open(FILES_TEMP, 'wb') as file:
                    while data:
                        file.write(data)
                        data = s.recv(1024)  

                return 'files.zip'
            elif data == b'NONE':
                return False
            
    def next_upd(self):
        username = self.lineEdit_2.text()

        if username:
            try:
                with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                    s.connect((HOST, PORT))
                    s.sendall(b'iu ' + bytes(self.key, 'UTF-8') + b' ' + bytes(username, 'UTF-8'))
                    data = s.recv(4)

                if data == b'TRUE':
                    with open(UPD_DATA, 'w') as file:
                        file.write(self.key + '\n' + username)

                    self.next_page()
                else:
                    self.attempts -= 1
                    if not self.attempts:
                        QMessageBox.critical(self, 'Ошибка', 'Слишком много неудачных попыток!')
                        self.pushButton_6.setDisabled(True)
                    else:
                        QMessageBox.critical(self, 'Ошибка', 'Неверный username.')
            except ConnectionRefusedError:
                QMessageBox.critical(self, 'Ошибка', 'Нет подключения к серверу.')
        else:
            QMessageBox.critical(self, 'Ошибка', 'Введите username!')
            
    def skip(self):
        with open(UPD_DATA, 'w') as file:
            file.write(self.key)

        self.next_page()

    def draw_icons(self):
        img1 = QImage(32, 32, QImage.Format.Format_RGBA64)
        img1.fill(QColor(0, 0, 0, 0))

        img2 = QImage(32, 32, QImage.Format.Format_RGBA64)
        img2.fill(QColor(0, 0, 0, 0))
        
        painter = QPainter()
        painter.begin(img1)

        painter.setPen(QColor(0, 0, 0, 0))
        painter.setBrush(QColor(255, 140, 0))
        painter.drawRect(4, 10, 6, 2)

        painter.setBrush(QColor(255, 255, 0))
        painter.drawEllipse(6, 6, 10, 10)
        painter.drawEllipse(6, 14, 20, 12)

        painter.setBrush(QColor(255, 255, 255))
        painter.setPen(QColor(255, 255, 255))
        painter.drawEllipse(8, 9, 2, 2)

        painter.setBrush(QColor(0, 0, 0))
        painter.setPen(QColor(0, 0, 0))
        painter.drawPoint(9, 10)

        painter.end()

        painter = QPainter()
        painter.begin(img2)

        painter.setBrush(QColor(0, 255, 0))
        painter.setPen(QColor(0, 255, 0))
        painter.drawLine(4, 16, 12, 26)
        painter.drawLine(12, 26, 20, 6)

        painter.end()

        pix1 = QPixmap.fromImage(img1)
        pix2 = QPixmap.fromImage(img2)

        self.label_3.setPixmap(pix1)
        self.label_11.setPixmap(pix2)
            

if __name__ == '__main__':
    app = QApplication(sys.argv)
    program = Installer()
    program.show()
    sys.exit(app.exec())